spring.application.name=practice

server.port=${PORT:8080}

# MySQL Configuration
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/silicon_2026}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:635635}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.validator.apply_to_ddl=false

# Remove this line (Hibernate detects the dialect automatically)
# spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=never
